"""Auto Queue Processor for PerryPicks v3.

Automatically processes queued posts to platforms without manual intervention.
Handles both immediate posting and scheduled posting.
"""

from __future__ import annotations
import logging
from typing import Dict, Any, List, Optional


from src.automation.post_queue import PostQueue, PostStatus
from src.automation.social_media_manager import SocialMediaManager

logger = logging.getLogger(__name__)


class AutoQueueProcessor:
    """Automatically process queued posts.
    
    Processes pending posts and sends them to platforms.
    Designed for automatic operation without manual intervention.
    """
    
    def __init__(
        self,
        social_manager: Optional[SocialMediaManager] = None,
    ):
        """Initialize auto queue processor.
        
        Args:
            social_manager: Social media manager instance
        """
        self.social_manager = social_manager
        self.queue = PostQueue() if not social_manager else social_manager.queue
        
        logger.info("Auto Queue Processor initialized")
    
    def queue_and_post(
        self,
        prediction: Dict[str, Any],
        trigger_type: str,
        platforms: Optional[List[str]] = None,
        max_retries: int = 3,
    ) -> Dict[str, Any]:
        """Queue prediction and immediately post it.
        
        Args:
            prediction: Prediction dictionary
            trigger_type: Type of trigger (halftime, q3, etc.)
            platforms: Platforms to post to
            max_retries: Max retries for failed posts
            
        Returns:
            Result dictionary with status
        """
        result = {
            "success": False,
            "queued": [],
            "posted": [],
            "errors": [],
        }
        
        game_id = prediction.get("game_id", "unknown")
        
        try:
            # Determine target platforms
            if platforms is None and self.social_manager:
                platforms = list(self.social_manager.enabled_platforms)
            
            if not platforms:
                logger.warning(f"No platforms available for {game_id}")
                result["error"] = "No platforms available"
                return result
            
            # Queue post for each platform
            queued_results = []
            for platform in platforms:
                try:
                    # Queue the post
                    post_id = self.queue.enqueue(
                        game_id=game_id,
                        platform=platform,
                        content="",  # Will be generated by social manager
                        trigger_type=trigger_type,
                        max_retries=max_retries,
                    )
                    
                    if post_id:
                        queued_results.append({
                            "platform": platform,
                            "post_id": post_id,
                            "status": "queued",
                        })
                        logger.info(f"Queued post for {game_id} on {platform}: {post_id}")
                    else:
                        queued_results.append({
                            "platform": platform,
                            "status": "duplicate",
                        })
                        logger.warning(f"Duplicate post detected for {game_id} on {platform}")
                
                except Exception as e:
                    logger.error(f"Error queueing post for {game_id} on {platform}: {e}")
                    result["errors"].append({
                        "platform": platform,
                        "error": str(e),
                    })
            
            result["queued"] = queued_results
            
            # Immediately process the queued posts
            if self.social_manager:
                process_result = self.social_manager.process_queue(
                    max_posts=len(queued_results),
                )
                
                result["posted"] = process_result.get("posts", [])
                result["success"] = process_result.get("success", False)
            
            return result
        
        except Exception as e:
            logger.error(f"Error in queue_and_post for {game_id}: {e}")
            result["error"] = str(e)
            return result
    
    def process_pending(self, max_posts: int = 10) -> Dict[str, Any]:
        """Process pending posts from queue.
        
        Args:
            max_posts: Maximum posts to process
            
        Returns:
            Processing results
        """
        try:
            if self.social_manager:
                return self.social_manager.process_queue(max_posts=max_posts)
            else:
                # No social manager - skip processing but don't fail
                # This allows queue processor to continue and retry when manager becomes available
                logger.warning("No social manager available - skipping queue processing (will retry)")
                return {
                    "success": True,  # Return success to avoid continuous error logging
                    "error": None,
                    "processed_predictions": 0,
                    "skipped": "No social manager available",
                }
        
        except Exception as e:
            logger.error(f"Error processing pending posts: {e}")
            return {"success": False, "error": str(e)}
    
    def get_queue_status(self) -> Dict[str, Any]:
        """Get current queue status.
        
        Returns:
            Dictionary with queue statistics
        """
        try:
            all_posts = self.queue.get_all_posts()
            pending_posts = [p for p in all_posts if p.status in (PostStatus.PENDING, PostStatus.POSTING)]
            failed_posts = [p for p in all_posts if p.status == PostStatus.FAILED]
            posted_posts = [p for p in all_posts if p.status == PostStatus.POSTED]
            
            return {
                "total": len(all_posts),
                "pending": len(pending_posts),
                "failed": len(failed_posts),
                "posted": len(posted_posts),
            }
        
        except Exception as e:
            logger.error(f"Error getting queue status: {e}")
            return {
                "total": 0,
                "pending": 0,
                "failed": 0,
                "posted": 0,
                "error": str(e),
            }