"""
Calibration validation for prediction intervals.

Implements coverage validation and calibration diagnostics
for prediction intervals generated by CQR or other methods.

Reference: execution_specification_for_statistically_valid_nba_forecasting_system.md Section 6.2
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple

from scipy import stats


def validate_coverage(
    y_true: np.ndarray,
    lower_pred: np.ndarray,
    upper_pred: np.ndarray,
    target_coverage: float = 0.9,
    n_bins: int = 10
) -> dict:
    """
    Validate coverage of prediction intervals.
    
    Args:
        y_true: True target values (n_samples,)
        lower_pred: Lower bound predictions (n_samples,)
        upper_pred: Upper bound predictions (n_samples,)
        target_coverage: Target coverage (default: 0.9 for 90%)
        n_bins: Number of bins for calibration curve
    
    Returns:
        Dictionary with coverage metrics and calibration diagnostics
    """
    # Check if y_true is within interval
    covered = (y_true >= lower_pred) & (y_true <= upper_pred)
    empirical_coverage = np.mean(covered)
    
    # Compute coverage error
    coverage_error = empirical_coverage - target_coverage
    
    # Perform binomial test for coverage
    n_samples = len(y_true)
    # Use binomtest for newer scipy versions
    try:
        p_value = stats.binomtest(
            k=np.sum(covered), n=n_samples, p=target_coverage, alternative='two-sided'
        ).pvalue
    except AttributeError:
        # Fallback for older scipy versions
        p_value = stats.binom_test(
            k=np.sum(covered), n=n_samples, p=target_coverage, alternative='two-sided'
        )
    
    # Compute confidence interval for empirical coverage
    # Using normal approximation
    se = np.sqrt(target_coverage * (1 - target_coverage) / n_samples)
    ci_lower = empirical_coverage - 1.96 * se
    ci_upper = empirical_coverage + 1.96 * se
    
    # Compute interval width metrics
    interval_widths = upper_pred - lower_pred
    mean_width = np.mean(interval_widths)
    median_width = np.median(interval_widths)
    std_width = np.std(interval_widths)
    
    # Calibration curve: coverage vs predicted confidence
    calibration_curve = compute_calibration_curve(
        y_true, lower_pred, upper_pred, n_bins=n_bins
    )
    
    return {
        "empirical_coverage": float(empirical_coverage),
        "target_coverage": target_coverage,
        "coverage_error": float(coverage_error),
        "p_value": float(p_value),
        "is_calibrated": abs(coverage_error) < 0.05,  # Within 5% tolerance
        "ci_lower": float(ci_lower),
        "ci_upper": float(ci_upper),
        "interval_width": {
            "mean": float(mean_width),
            "median": float(median_width),
            "std": float(std_width),
        },
        "calibration_curve": calibration_curve,
        "n_samples": n_samples,
    }


def compute_calibration_curve(
    y_true: np.ndarray,
    lower_pred: np.ndarray,
    upper_pred: np.ndarray,
    n_bins: int = 10
) -> List[dict]:
    """
    Compute calibration curve: empirical coverage vs predicted confidence.
    
    For each bin, compute the predicted confidence (based on interval width)
    and the empirical coverage (fraction of points covered).
    
    Args:
        y_true: True target values (n_samples,)
        lower_pred: Lower bound predictions (n_samples,)
        upper_pred: Upper bound predictions (n_samples,)
        n_bins: Number of bins for calibration curve
    
    Returns:
        List of dicts with bin metrics
    """
    # Compute interval widths
    interval_widths = upper_pred - lower_pred
    
    # Create bins based on interval widths
    width_bins = np.percentile(interval_widths, np.linspace(0, 100, n_bins + 1))
    
    calibration_curve = []
    
    for i in range(n_bins):
        # Get points in this bin
        in_bin = (interval_widths >= width_bins[i]) & (interval_widths < width_bins[i + 1])
        
        if i == n_bins - 1:  # Include upper edge in last bin
            in_bin = (interval_widths >= width_bins[i]) & (interval_widths <= width_bins[i + 1])
        
        if np.sum(in_bin) == 0:
            continue
        
        # Compute empirical coverage for this bin
        covered = (y_true[in_bin] >= lower_pred[in_bin]) & (y_true[in_bin] <= upper_pred[in_bin])
        empirical_coverage_bin = np.mean(covered)
        
        # Predicted confidence (inverse of normalized width)
        # Use relative width: width / max_width
        max_width = np.max(width_bins)
        relative_width = width_bins[i] / max_width
        
        # Inverse: wider intervals should have higher confidence
        predicted_confidence = 1.0 - relative_width
        
        calibration_curve.append({
            "bin": i,
            "width_lower": float(width_bins[i]),
            "width_upper": float(width_bins[i + 1]),
            "n_points": int(np.sum(in_bin)),
            "predicted_confidence": float(predicted_confidence),
            "empirical_coverage": float(empirical_coverage_bin),
        })
    
    return calibration_curve


def compute_calibration_error(
    calibration_curve: List[dict]
) -> dict:
    """
    Compute calibration error metrics.
    
    Metrics:
    - Expected Calibration Error (ECE)
    - Maximum Calibration Error (MCE)
    - Brier score
    
    Args:
        calibration_curve: Calibration curve from compute_calibration_curve()
    
    Returns:
        Dictionary with calibration error metrics
    """
    if not calibration_curve:
        return {
            "ece": float('nan'),
            "mce": float('nan'),
            "n_bins": 0,
        }
    
    # Expected Calibration Error (ECE)
    ece = 0.0
    total_points = sum(bin_dict["n_points"] for bin_dict in calibration_curve)
    
    for bin_dict in calibration_curve:
        weight = bin_dict["n_points"] / total_points
        error = abs(bin_dict["empirical_coverage"] - bin_dict["predicted_confidence"])
        ece += weight * error
    
    # Maximum Calibration Error (MCE)
    mce = max(
        abs(bin_dict["empirical_coverage"] - bin_dict["predicted_confidence"])
        for bin_dict in calibration_curve
    )
    
    return {
        "ece": float(ece),
        "mce": float(mce),
        "n_bins": len(calibration_curve),
    }


def validate_uncertainty_report(
    y_true: np.ndarray,
    lower_pred: np.ndarray,
    upper_pred: np.ndarray,
    target_coverage: float = 0.9
) -> str:
    """
    Generate human-readable validation report.
    
    Args:
        y_true: True target values
        lower_pred: Lower bound predictions
        upper_pred: Upper bound predictions
        target_coverage: Target coverage
    
    Returns:
        Formatted report string
    """
    results = validate_coverage(
        y_true, lower_pred, upper_pred, target_coverage=target_coverage
    )
    
    calibration_error = compute_calibration_error(results["calibration_curve"])
    
    lines = [
        "=" * 80,
        "CALIBRATION VALIDATION REPORT",
        "=" * 80,
        "",
        f"Target Coverage: {target_coverage:.1%}",
        f"Empirical Coverage: {results['empirical_coverage']:.1%}",
        f"Coverage Error: {results['coverage_error']:.1%}",
        f"P-Value (binomial test): {results['p_value']:.4f}",
        f"Is Calibrated (5% tolerance): {results['is_calibrated']}",
        "",
        f"Coverage CI (95%): [{results['ci_lower']:.1%}, {results['ci_upper']:.1%}]",
        "",
        f"Interval Width Statistics:",
        f"  Mean: {results['interval_width']['mean']:.4f}",
        f"  Median: {results['interval_width']['median']:.4f}",
        f"  Std: {results['interval_width']['std']:.4f}",
        "",
        f"Calibration Error Metrics:",
        f"  Expected Calibration Error (ECE): {calibration_error['ece']:.4f}",
        f"  Maximum Calibration Error (MCE): {calibration_error['mce']:.4f}",
        "",
        f"Calibration Curve (Coverage vs Predicted Confidence):",
        f"  Bin | Width Range | Points | Pred Conf | Emp Cov",
    ]
    
    for bin_dict in results["calibration_curve"]:
        lines.append(
            f"  {bin_dict['bin']:3d} | "
            f"[{bin_dict['width_lower']:.2f}, {bin_dict['width_upper']:.2f}) | "
            f"{bin_dict['n_points']:6d} | "
            f"{bin_dict['predicted_confidence']:.2%} | "
            f"{bin_dict['empirical_coverage']:.2%}"
        )
    
    lines.append("")
    lines.append("=" * 80)
    
    return "\n".join(lines)


if __name__ == "__main__":
    # Test calibration validation
    print("Testing calibration validation...")
    
    import sys
    sys.path.insert(0, "/Users/jarrydhawley/Desktop/Predictor/PerryPicks v3")
    
    from src.conformal.cqr import conformalized_quantile_regression, predict_intervals
    from sklearn.impute import SimpleImputer
    
    df = pd.read_parquet(
        "/Users/jarrydhawley/Desktop/Predictor/PerryPicks v3/data/processed/halftime_with_temporal_features_total.parquet"
    )
    print(f"Loaded dataset: {len(df)} rows, {len(df.columns)} columns")
    
    # Select features and target
    h1_features = [col for col in df.columns if col.startswith('h1_')]
    target = 'h2_total'
    
    # Prepare data
    X = df[h1_features].values
    y = df[target].values
    
    # Impute missing values
    imputer = SimpleImputer(strategy='median')
    X = imputer.fit_transform(X)
    
    # Run CQR
    cqr_results = conformalized_quantile_regression(
        X, y, alpha=0.1, random_state=42, test_size=0.2
    )
    
    # Generate intervals for calibration set
    X_cal = X[cqr_results['cal_idx']]
    y_cal = y[cqr_results['cal_idx']]
    
    lower_pred, upper_pred = predict_intervals(cqr_results, X_cal)
    
    # Validate coverage
    print(validate_uncertainty_report(y_cal, lower_pred, upper_pred, target_coverage=0.9))
